# Generated by Django 2.0.6 on 2018-07-12 14:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0002_profile_affiliation'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='University',
            new_name='Organization',
        ),
    ]
