# Generated by Django 2.0.6 on 2018-07-17 19:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0003_auto_20180712_1054'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='vehicle',
            field=models.CharField(default='', max_length=100),
        ),
    ]
