# Generated by Django 2.0.6 on 2018-07-20 14:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0006_profile_phone_number'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='org_email',
            field=models.CharField(default='', max_length=100),
        ),
    ]
