# Generated by Django 2.0.6 on 2018-07-22 16:45

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0009_auto_20180721_2257'),
    ]

    operations = [
        migrations.AlterField(
            model_name='message',
            name='timestamp',
            field=models.TimeField(default=datetime.datetime.now),
        ),
    ]
