# Generated by Django 2.0.6 on 2018-07-22 16:59

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0012_auto_20180722_1252'),
    ]

    operations = [
        migrations.AlterField(
            model_name='message',
            name='timestamp',
            field=models.DateTimeField(default=datetime.datetime(2018, 7, 22, 16, 59, 57, 681591, tzinfo=utc)),
        ),
    ]
