# Generated by Django 2.0.6 on 2018-07-24 19:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0017_auto_20180724_1236'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='major',
            field=models.CharField(blank=True, default='', max_length=100, null=True),
        ),
    ]
