# Generated by Django 2.0.6 on 2018-07-26 17:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0019_organization_domain'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='phone_number',
            field=models.CharField(default='555-555-5555', max_length=17),
        ),
    ]
