# Generated by Django 2.0.6 on 2018-07-30 02:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0021_auto_20180729_2227'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='car',
            field=models.OneToOneField(default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='profiles.Car'),
        ),
    ]
