# Generated by Django 2.0.6 on 2018-07-30 02:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0022_auto_20180729_2233'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='car',
            name='year',
        ),
        migrations.AlterField(
            model_name='car',
            name='make',
            field=models.CharField(default='Honda', max_length=100),
        ),
        migrations.AlterField(
            model_name='car',
            name='model',
            field=models.CharField(default='Civic', max_length=100),
        ),
        migrations.AlterField(
            model_name='car',
            name='plate',
            field=models.CharField(default='XXX-XXXX', max_length=10),
        ),
    ]
