# Generated by Django 2.0.6 on 2018-07-10 16:00

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('treks', '0002_auto_20180709_1741'),
    ]

    operations = [
        migrations.AddField(
            model_name='trek',
            name='date',
            field=models.DateField(default=datetime.date.today),
        ),
        migrations.AddField(
            model_name='trek',
            name='time',
            field=models.TimeField(default=datetime.datetime(2018, 7, 10, 16, 0, 43, 788126, tzinfo=utc)),
        ),
    ]
