# Generated by Django 2.0.6 on 2018-07-10 16:01

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('treks', '0003_auto_20180710_1200'),
    ]

    operations = [
        migrations.AlterField(
            model_name='trek',
            name='time',
            field=models.TimeField(default=django.utils.timezone.now),
        ),
    ]
