# Generated by Django 2.0.6 on 2018-07-10 16:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('treks', '0004_auto_20180710_1201'),
    ]

    operations = [
        migrations.AddField(
            model_name='trek',
            name='destination',
            field=models.CharField(default='LOJ', max_length=100),
        ),
        migrations.AddField(
            model_name='trek',
            name='source',
            field=models.CharField(default='Tufts University', max_length=100),
        ),
    ]
