# Generated by Django 2.0.6 on 2018-07-17 00:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('treks', '0006_auto_20180712_1547'),
    ]

    operations = [
        migrations.AlterField(
            model_name='trek',
            name='vehicle',
            field=models.ForeignKey(default=2, on_delete=django.db.models.deletion.PROTECT, to='treks.Car'),
        ),
    ]
