# Generated by Django 2.0.6 on 2018-07-17 14:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('treks', '0007_auto_20180716_2043'),
    ]

    operations = [
        migrations.AddField(
            model_name='trek',
            name='note',
            field=models.TextField(default=''),
        ),
    ]
