# Generated by Django 2.0.6 on 2018-07-17 14:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('treks', '0008_trek_note'),
    ]

    operations = [
        migrations.AddField(
            model_name='trek',
            name='seats',
            field=models.IntegerField(default='3'),
        ),
        migrations.AddField(
            model_name='trek',
            name='seats_taken',
            field=models.IntegerField(default='0'),
        ),
    ]
