# Generated by Django 2.0.6 on 2018-07-17 15:21

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('treks', '0009_auto_20180717_1058'),
    ]

    operations = [
        migrations.RenameField(
            model_name='trek',
            old_name='time',
            new_name='departure_time',
        ),
        migrations.AddField(
            model_name='trek',
            name='arrival_time',
            field=models.TimeField(default=django.utils.timezone.now),
        ),
    ]
