# Generated by Django 2.0.6 on 2018-07-17 19:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('treks', '0010_auto_20180717_1121'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='trek',
            name='seats_taken',
        ),
        migrations.RemoveField(
            model_name='trek',
            name='vehicle',
        ),
        migrations.DeleteModel(
            name='Car',
        ),
    ]
