# Generated by Django 2.0.6 on 2018-07-18 18:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('treks', '0011_auto_20180717_1513'),
    ]

    operations = [
        migrations.AddField(
            model_name='trek',
            name='dropoff',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='trek',
            name='dropoff_radius',
            field=models.IntegerField(default=1),
        ),
        migrations.AddField(
            model_name='trek',
            name='edu_only',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='trek',
            name='fem_only',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='trek',
            name='flexible_departure',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='trek',
            name='mutuals_only',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='trek',
            name='org_only',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='trek',
            name='pickup',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='trek',
            name='pickup_radius',
            field=models.IntegerField(default=1),
        ),
    ]
