# Generated by Django 2.0.6 on 2018-07-22 20:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('treks', '0013_auto_20180718_1508'),
    ]

    operations = [
        migrations.AlterField(
            model_name='trek',
            name='from_addr',
            field=models.CharField(blank=True, default='', max_length=100),
        ),
        migrations.AlterField(
            model_name='trek',
            name='to_addr',
            field=models.CharField(blank=True, default='', max_length=100),
        ),
    ]
