# Generated by Django 2.0.6 on 2018-07-30 04:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('treks', '0014_auto_20180722_1613'),
    ]

    operations = [
        migrations.AlterField(
            model_name='trek',
            name='price',
            field=models.IntegerField(default='20'),
        ),
    ]
