# Generated by Django 2.0.6 on 2018-07-30 04:29

import datetime
from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('treks', '0015_auto_20180730_0026'),
    ]

    operations = [
        migrations.CreateModel(
            name='Request',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(default=datetime.date.today)),
                ('departure_time', models.TimeField(default=django.utils.timezone.now)),
                ('flexible_departure', models.BooleanField(default=True)),
                ('arrival_time', models.TimeField(default=django.utils.timezone.now)),
                ('from_addr', models.CharField(blank=True, default='', max_length=100)),
                ('from_city', models.CharField(default='Medford', max_length=100)),
                ('from_state', models.CharField(default='MA', max_length=2)),
                ('to_addr', models.CharField(blank=True, default='', max_length=100)),
                ('to_city', models.CharField(default='Woodstock', max_length=100)),
                ('to_state', models.CharField(default='NH', max_length=100)),
                ('pickup', models.BooleanField(default=False)),
                ('pickup_radius', models.IntegerField(default=5)),
                ('dropoff', models.BooleanField(default=False)),
                ('dropoff_radius', models.IntegerField(default=5)),
                ('note', models.TextField(default='')),
                ('fem_only', models.BooleanField(default=False)),
                ('org_only', models.BooleanField(default=False)),
                ('edu_only', models.BooleanField(default=False)),
                ('mutuals_only', models.BooleanField(default=False)),
            ],
        ),
    ]
